rss_list:
    - topic_id: Blog
      topic_list:
          - feed_id: rust-blog
            feed_url: https://blog.rust-lang.org/feed.xml
          - feed_id: rust-blog-inside
            feed_url: https://blog.rust-lang.org/inside-rust/feed.xml
          - feed_id: jetbrains-kotlin-blog
            feed_url: https://blog.jetbrains.com/kotlin/feed/
          - feed_id: oracle-java-blog
            feed_url: https://blogs.oracle.com/java/rss
          - feed_id: oracle-java-blog-inside
            feed_url: https://inside.java/feed.xml
          - feed_id: ubuntu-blog
            feed_url: https://ubuntu.com/blog/feed
          - feed_id: thoughtworks
            feed_url: https://www.thoughtworks.com/rss/engineering.xml
    #- topic_id: Conf
    #  topic_list:
    #- feed_id: conpass
    #  feed_url: https://connpass.com/explore/ja.atom
